/**
 * CDS Hooks
 * The following is auto generated class definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CdsServiceResponseCardSourceJson } from './cdsServiceResponseCardSourceJson';
import { CdsServiceResponseCodingJson } from './cdsServiceResponseCodingJson';
import { CdsServiceResponseLinkJson } from './cdsServiceResponseLinkJson';
import { CdsServiceResponseSuggestionJson } from './cdsServiceResponseSuggestionJson';

export interface CdsServiceResponseCardJson { 
    extension: any;
    uuid?: string;
    summary: string;
    detail?: string;
    indicator: CdsServiceResponseCardJson.IndicatorEnum;
    source: CdsServiceResponseCardSourceJson;
    suggestions?: Array<CdsServiceResponseSuggestionJson>;
    selectionBehavior?: string;
    overrideReasons?: Array<CdsServiceResponseCodingJson>;
    links?: Array<CdsServiceResponseLinkJson>;
}
export namespace CdsServiceResponseCardJson {
    export type IndicatorEnum = 'info' | 'warning' | 'critical';
    export const IndicatorEnum = {
        Info: 'info' as IndicatorEnum,
        Warning: 'warning' as IndicatorEnum,
        Critical: 'critical' as IndicatorEnum
    };
}