/**
 * CDS Hooks
 * The following is auto generated class definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CdsServiceResponseCodingJson } from './cdsServiceResponseCodingJson';

export interface CdsServiceResponseCardSourceJson { 
    label: string;
    url?: string;
    icon?: string;
    topic?: CdsServiceResponseCodingJson;
}