/**
 * FHIR Version R5
 * The following is auto generated resource definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { Canonical } from './canonical';
import { Code } from './code';
import { CodeableConcept } from './codeableConcept';
import { CodeableReference } from './codeableReference';
import { CommunicationPayload } from './communicationPayload';
import { DateTime } from './dateTime';
import { Extension } from './extension';
import { Id } from './id';
import { Identifier } from './identifier';
import { Meta } from './meta';
import { Narrative } from './narrative';
import { Reference } from './reference';
import { ResourceList } from './resourceList';
import { Uri } from './uri';

/**
 * A clinical or business level record of information being transmitted or shared; e.g. an alert that was sent to a responsible provider, a public health agency communication to a provider/reporter in response to a case report for a reportable condition.
 */
export interface Communication { 
    /**
     * This is a Communication resource
     */
    resourceType: 'Communication';
    id?: Id;
    meta?: Meta;
    implicitRules?: Uri;
    language?: Code;
    text?: Narrative;
    /**
     * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.
     */
    contained?: Array<ResourceList>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
     */
    extension?: Array<Extension>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
     */
    modifierExtension?: Array<Extension>;
    /**
     * Business identifiers assigned to this communication by the performer or other systems which remain constant as the resource is updated and propagates from server to server.
     */
    identifier?: Array<Identifier>;
    /**
     * The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.
     */
    instantiatesCanonical?: Array<Canonical>;
    /**
     * The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.
     */
    instantiatesUri?: Array<Uri>;
    /**
     * An order, proposal or plan fulfilled in whole or in part by this Communication.
     */
    basedOn?: Array<Reference>;
    /**
     * A larger event (e.g. Communication, Procedure) of which this particular communication is a component or step.
     */
    partOf?: Array<Reference>;
    /**
     * Prior communication that this communication is in response to.
     */
    inResponseTo?: Array<Reference>;
    status?: Code;
    statusReason?: CodeableConcept;
    /**
     * The type of message conveyed such as alert, notification, reminder, instruction, etc.
     */
    category?: Array<CodeableConcept>;
    priority?: Code;
    /**
     * A channel that was used for this communication (e.g. email, fax).
     */
    medium?: Array<CodeableConcept>;
    subject?: Reference;
    topic?: CodeableConcept;
    /**
     * Other resources that pertain to this communication and to which this communication should be associated.
     */
    about?: Array<Reference>;
    encounter?: Reference;
    sent?: Date;
    received?: Date;
    /**
     * The entity (e.g. person, organization, clinical information system, care team or device) which is the target of the communication.
     */
    recipient?: Array<Reference>;
    sender?: Reference;
    /**
     * The reason or justification for the communication.
     */
    reason?: Array<CodeableReference>;
    /**
     * Text, attachment(s), or resource(s) that was communicated to the recipient.
     */
    payload?: Array<CommunicationPayload>;
    /**
     * Additional notes or commentary about the communication by the sender, receiver or other interested parties.
     */
    note?: Array<Annotation>;
}