/**
 * FHIR Version R5
 * The following is auto generated resource definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeableConcept } from './codeableConcept';
import { Extension } from './extension';
import { Identifier } from './identifier';
import { InsurancePlanGeneralCost } from './insurancePlanGeneralCost';
import { InsurancePlanSpecificCost } from './insurancePlanSpecificCost';
import { Reference } from './reference';

/**
 * Details of a Health Insurance product/plan provided by an organization.
 */
export interface InsurancePlanPlan { 
    id?: string;
    /**
     * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
     */
    extension?: Array<Extension>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
     */
    modifierExtension?: Array<Extension>;
    /**
     * Business identifiers assigned to this health insurance plan which remain constant as the resource is updated and propagates from server to server.
     */
    identifier?: Array<Identifier>;
    type?: CodeableConcept;
    /**
     * The geographic region in which a health insurance plan's benefits apply.
     */
    coverageArea?: Array<Reference>;
    /**
     * Reference to the network that providing the type of coverage.
     */
    network?: Array<Reference>;
    /**
     * Overall costs associated with the plan.
     */
    generalCost?: Array<InsurancePlanGeneralCost>;
    /**
     * Costs associated with the coverage provided by the product.
     */
    specificCost?: Array<InsurancePlanSpecificCost>;
}