/**
 * FHIR Version R5
 * The following is auto generated resource definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { Canonical } from './canonical';
import { Code } from './code';
import { CodeableConcept } from './codeableConcept';
import { CodeableReference } from './codeableReference';
import { DateTime } from './dateTime';
import { Extension } from './extension';
import { Id } from './id';
import { Identifier } from './identifier';
import { Meta } from './meta';
import { Narrative } from './narrative';
import { NutritionIntakeConsumedItem } from './nutritionIntakeConsumedItem';
import { NutritionIntakeIngredientLabel } from './nutritionIntakeIngredientLabel';
import { NutritionIntakePerformer } from './nutritionIntakePerformer';
import { Period } from './period';
import { Reference } from './reference';
import { ResourceList } from './resourceList';
import { Uri } from './uri';

/**
 * A record of food or fluid that is being consumed by a patient.   A NutritionIntake may indicate that the patient may be consuming the food or fluid now or has consumed the food or fluid in the past.  The source of this information can be the patient, significant other (such as a family member or spouse), or a clinician.  A common scenario where this information is captured is during the history taking process during a patient visit or stay or through an app that tracks food or fluids consumed.   The consumption information may come from sources such as the patient's memory, from a nutrition label,  or from a clinician documenting observed intake.
 */
export interface NutritionIntake { 
    /**
     * This is a NutritionIntake resource
     */
    resourceType: 'NutritionIntake';
    id?: Id;
    meta?: Meta;
    implicitRules?: Uri;
    language?: Code;
    text?: Narrative;
    /**
     * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.
     */
    contained?: Array<ResourceList>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
     */
    extension?: Array<Extension>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
     */
    modifierExtension?: Array<Extension>;
    /**
     * Identifiers associated with this Nutrition Intake that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are business identifiers assigned to this resource by the performer or other systems and remain constant as the resource is updated and propagates from server to server.
     */
    identifier?: Array<Identifier>;
    /**
     * Instantiates FHIR protocol or definition.
     */
    instantiatesCanonical?: Array<Canonical>;
    /**
     * Instantiates external protocol or definition.
     */
    instantiatesUri?: Array<Uri>;
    /**
     * A plan, proposal or order that is fulfilled in whole or in part by this event.
     */
    basedOn?: Array<Reference>;
    /**
     * A larger event of which this particular event is a component or step.
     */
    partOf?: Array<Reference>;
    status?: Code;
    /**
     * Captures the reason for the current state of the NutritionIntake.
     */
    statusReason?: Array<CodeableConcept>;
    code?: CodeableConcept;
    subject: Reference;
    encounter?: Reference;
    /**
     * The interval of time during which it is being asserted that the patient is/was consuming the food or fluid.
     */
    occurrenceDateTime?: string;
    occurrencePeriod?: Period;
    recorded?: Date;
    /**
     * The person or organization that provided the information about the consumption of this food or fluid. Note: Use derivedFrom when a NutritionIntake is derived from other resources.
     */
    reportedBoolean?: boolean;
    reportedReference?: Reference;
    /**
     * What food or fluid product or item was consumed.
     */
    consumedItem: Array<NutritionIntakeConsumedItem>;
    /**
     * Total nutrient amounts for the whole meal, product, serving, etc.
     */
    ingredientLabel?: Array<NutritionIntakeIngredientLabel>;
    /**
     * Who performed the intake and how they were involved.
     */
    performer?: Array<NutritionIntakePerformer>;
    location?: Reference;
    /**
     * Allows linking the NutritionIntake to the underlying NutritionOrder, or to other information, such as AllergyIntolerance, that supports or is used to derive the NutritionIntake.
     */
    derivedFrom?: Array<Reference>;
    /**
     * A reason, Condition or observation for why the food or fluid is /was consumed.
     */
    reason?: Array<CodeableReference>;
    /**
     * Provides extra information about the Nutrition Intake that is not conveyed by the other attributes.
     */
    note?: Array<Annotation>;
}