/**
 * FHIR Version R5
 * The following is auto generated resource definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Annotation } from './annotation';
import { Canonical } from './canonical';
import { Code } from './code';
import { CodeableConcept } from './codeableConcept';
import { CodeableReference } from './codeableReference';
import { DateTime } from './dateTime';
import { Extension } from './extension';
import { Id } from './id';
import { Identifier } from './identifier';
import { Meta } from './meta';
import { Narrative } from './narrative';
import { Reference } from './reference';
import { RequestOrchestrationAction } from './requestOrchestrationAction';
import { ResourceList } from './resourceList';
import { Uri } from './uri';

/**
 * A set of related requests that can be used to capture intended activities that have inter-dependencies such as \"give this medication after that one\".
 */
export interface RequestOrchestration { 
    /**
     * This is a RequestOrchestration resource
     */
    resourceType: any;
    id?: Id;
    meta?: Meta;
    implicitRules?: Uri;
    language?: Code;
    text?: Narrative;
    /**
     * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.
     */
    contained?: Array<ResourceList>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
     */
    extension?: Array<Extension>;
    /**
     * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
     */
    modifierExtension?: Array<Extension>;
    /**
     * Allows a service to provide a unique, business identifier for the request.
     */
    identifier?: Array<Identifier>;
    /**
     * A canonical URL referencing a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this request.
     */
    instantiatesCanonical?: Array<Canonical>;
    /**
     * A URL referencing an externally defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this request.
     */
    instantiatesUri?: Array<Uri>;
    /**
     * A plan, proposal or order that is fulfilled in whole or in part by this request.
     */
    basedOn?: Array<Reference>;
    /**
     * Completed or terminated request(s) whose function is taken by this new request.
     */
    replaces?: Array<Reference>;
    groupIdentifier?: Identifier;
    status?: Code;
    intent?: Code;
    priority?: Code;
    code?: CodeableConcept;
    subject?: Reference;
    encounter?: Reference;
    authoredOn?: Date;
    author?: Reference;
    /**
     * Describes the reason for the request orchestration in coded or textual form.
     */
    reason?: Array<CodeableReference>;
    /**
     * Goals that are intended to be achieved by following the requests in this RequestOrchestration.
     */
    goal?: Array<Reference>;
    /**
     * Provides a mechanism to communicate additional information about the response.
     */
    note?: Array<Annotation>;
    /**
     * The actions, if any, produced by the evaluation of the artifact.
     */
    action?: Array<RequestOrchestrationAction>;
}