/**
 * FHIR Version R5
 * The following is auto generated resource definition.
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coding } from './coding';
import { ContactPoint } from './contactPoint';
import { ExtendedContactDetail } from './extendedContactDetail';
import { Extension } from './extension';
import { PositiveInt } from './positiveInt';
import { Url } from './url';

/**
 * Virtual Service Contact Details.
 */
export interface VirtualServiceDetail { 
    id?: string;
    /**
     * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
     */
    extension?: Array<Extension>;
    channelType?: Coding;
    /**
     * What address or number needs to be used for a user to connect to the virtual service to join. The channelType informs as to which datatype is appropriate to use (requires knowledge of the specific type).
     */
    addressUrl?: string;
    /**
     * What address or number needs to be used for a user to connect to the virtual service to join. The channelType informs as to which datatype is appropriate to use (requires knowledge of the specific type).
     */
    addressString?: string;
    addressContactPoint?: ContactPoint;
    addressExtendedContactDetail?: ExtendedContactDetail;
    /**
     * Address to see alternative connection details.
     */
    additionalInfo?: Array<Url>;
    maxParticipants?: PositiveInt;
    sessionKey?: string;
}